### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by rishabmahesh** [tim-we/esbuild-plugin-svg-bundle#51]
Hello,

Can you please make an example project and upload that to your project? I'm trying to use this library, and I'm not able to get it to work. (I'm VERY new to esbuild)

Thank you!

**Comment by tim-we** [comment]
Hey there, I will give that a shot. Haven't touched and used this code in a while though, if there are non-trivial problems it probably won't happen.

**Comment by tim-we** [comment]
I have added a very basic example: https://github.com/tim-we/esbuild-plugin-svg-bundle/tree/main/example

Hope this helps ;)
